insert into AUTHORS (id, name, birthdate) values (1, 'King', TO_TIMESTAMP('1947.09.21 10:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF'))
insert into AUTHORS (id, name, birthdate) values (2, 'Kipling', TO_TIMESTAMP('1865.12.30 10:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF'))
insert into AUTHORS (id, name, birthdate) values (3, 'J. R. R. Tolkien', TO_TIMESTAMP('1892.01.03 10:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF'))
insert into AUTHORS (id, name, birthdate) values (4, 'J. Swift', TO_TIMESTAMP('1667.11.30 10:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF'))
insert into AUTHORS (id, name, birthdate) values (5, 'George Gordon Byron', TO_TIMESTAMP('1788.01.22 10:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF'))
insert into AUTHORS (id, name, birthdate) values (6, 'L. Tolstoy', TO_TIMESTAMP('1828.09.09 10:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF'))
insert into AUTHORS (id, name, birthdate) values (7, 'A. Pushkin', TO_TIMESTAMP('1799.06.06 10:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF'))
insert into AUTHORS (id, name, birthdate) values (8, 'A. Dumas', TO_TIMESTAMP('1802.07.24 10:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF'))
insert into AUTHORS (id, name, birthdate) values (9, 'J. Verne', TO_TIMESTAMP('1828.02.08 10:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF'))
insert into AUTHORS (id, name, birthdate) values (10, 'S. Marshak', TO_TIMESTAMP('1887.11.03 10:00:00.00', 'YYYY-MM-DD HH24:MI:SS.FF'))

insert into GENRES (id, name, description) values (1, 'Thriller', 'like Hitchcock horror')
insert into GENRES (id, name, description) values (2, 'Drama', 'soap opera')
insert into GENRES (id, name, description) values (3, 'Poetry', 'Poetry')
insert into GENRES (id, name, description) values (4, 'Novel', 'Novel')
insert into GENRES (id, name, description) values (5, 'Detective', 'criminal')
insert into GENRES (id, name, description) values (6, 'Comics', 'literature for children')
insert into GENRES (id, name, description) values (7, 'Journal', '')
insert into GENRES (id, name, description) values (8, 'Science', 'scientific literature')
insert into GENRES (id, name, description) values (9, 'Adventures', 'Adventures')
insert into GENRES (id, name, description) values (10, 'Tragedy', 'melancholy')
