DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID      BIGINT NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR(255),
    BIRTHDATE TIMESTAMP,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID      BIGINT NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR(255),
    DESCRIPTION    VARCHAR(255),
    PRIMARY KEY (ID)
);