spring:
  application:
    name: book-price-service
  datasource:
    url: jdbc:h2:mem:price
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db.changelog-master.xml
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true

locale: ru

logging:
  level:
    ROOT: ERROR

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:7002/eureka}
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    leaseExpirationDurationInSeconds: 90
    leaseRenewalIntervalInSeconds: 30
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 15000

server:
  port: ${EXTERNAL_REFERENCE_PORT:7004}

management:
  endpoints:
    web:
      exposure:
        include: '*'
